import { NgModule } from '@angular/core';
import {
    IconCamera,
    IconHeart,
    IconGithub,
    IconFileText,
    IconLayers,
    IconUpload,
    IconSend,
    IconTrendingUp,
    IconDownload,
    IconBox,
    IconXSquare,
    IconChevronDown,
    IconChevronUp,
    IconPlusSquare,
    IconFilter,
    IconSearch,
    IconInfo,
    IconChevronLeft,
    IconChevronRight,
    IconSquare,
    IconCheckCircle,
    IconMinusSquare,
    IconShare2,
    IconShoppingCart,
    IconEdit,
    IconCheck,
    IconDownloadCloud,
    IconAirplay,
    IconCheckSquare,
    IconEye,
    IconEyeOff,
    IconArrowRightCircle,
    IconArrowLeftCircle,
    IconXCircle,
    IconX,
    IconLink2,
    IconRotateCcw,
    IconRotateCw,
    IconSettings,
    IconUser,
    IconArrowDownCircle,
    IconArrowUpCircle
} from 'angular-feather';
/* import { IconX } from 'angular-feather/feather/x'; */

const icons = [
    IconCamera,
    IconBox,
    IconHeart,
    IconGithub,
    IconFileText,
    IconLayers,
    IconUpload,
    IconSend,
    IconTrendingUp,
    IconDownload,
    IconXSquare,
    IconChevronDown,
    IconChevronUp,
    IconPlusSquare,
    IconFilter,
    IconSearch,
    IconInfo,
    IconChevronLeft,
    IconChevronRight,
    IconSquare,
    IconCheckCircle,
    IconMinusSquare,
    IconShare2,
    IconXSquare,
    IconShoppingCart,
    IconEdit,
    IconCheck,
    IconDownloadCloud,
    IconAirplay,
    IconCheckSquare,
    IconEye,
    IconEyeOff,
    IconArrowRightCircle,
    IconArrowLeftCircle,
    IconXCircle,
    IconX,
    IconLink2,
    IconRotateCcw,
    IconRotateCw,
    IconSettings,
    IconUser,
    IconArrowDownCircle,
    IconArrowUpCircle
];

@NgModule({
    exports: icons
})
export class IconsModule {}
