import { QuestionBase } from './question-base';

export class CountryLists extends QuestionBase<string> {
    controlType = 'country';
    options = [
        { key: 'Afg', value: 'Afghanistan' },
        { key: 'Åla', value: 'Åland Islands' },
        { key: 'Alb', value: 'Albania' },
        { key: 'Alg', value: 'Algeria' },
        { key: 'Ame', value: 'American Samoa' },
        { key: 'And', value: 'Andorra' },
        { key: 'Ang', value: 'Angola' },
        { key: 'Ang', value: 'Anguilla' },
        { key: 'Ant', value: 'Antarctica' },
        { key: 'Ant', value: 'Antigua and Barbuda' },
        { key: 'Arg', value: 'Argentina' },
        { key: 'Arm', value: 'Armenia' },
        { key: 'Aru', value: 'Aruba' },
        { key: 'Aus', value: 'Australia' },
        { key: 'Aus', value: 'Austria' },
        { key: 'Aze', value: 'Azerbaijan' },
        { key: 'Bah', value: 'Bahamas' },
        { key: 'Bah', value: 'Bahrain' },
        { key: 'Ban', value: 'Bangladesh' },
        { key: 'Bar', value: 'Barbados' },
        { key: 'Bel', value: 'Belarus' },
        { key: 'Bel', value: 'Belgium' },
        { key: 'Bel', value: 'Belize' },
        { key: 'Ben', value: 'Benin' },
        { key: 'Ber', value: 'Bermuda' },
        { key: 'Bhu', value: 'Bhutan' },
        { key: 'Bol', value: 'Bolivia, Plurinational State of' },
        { key: 'Bon', value: 'Bonaire, Sint Eustatius and Saba' },
        { key: 'Bos', value: 'Bosnia and Herzegovina' },
        { key: 'Bot', value: 'Botswana' },
        { key: 'Bou', value: 'Bouvet Island' },
        { key: 'Bra', value: 'Brazil' },
        { key: 'Bri', value: 'British Indian Ocean Territory' },
        { key: 'Bru', value: 'Brunei Darussalam' },
        { key: 'Bul', value: 'Bulgaria' },
        { key: 'Bur', value: 'Burkina Faso' },
        { key: 'Bur', value: 'Burundi' },
        { key: 'Cam', value: 'Cambodia' },
        { key: 'Cam', value: 'Cameroon' },
        { key: 'Can', value: 'Canada' },
        { key: 'Cap', value: 'Cape Verde' },
        { key: 'Cay', value: 'Cayman Islands' },
        { key: 'Cen', value: 'Central African Republic' },
        { key: 'Cha', value: 'Chad' },
        { key: 'Chi', value: 'Chile' },
        { key: 'Chi', value: 'China' },
        { key: 'Chr', value: 'Christmas Island' },
        { key: 'Coc', value: 'Cocos(Keeling) Islands' },
        { key: 'Col', value: 'Colombia' },
        { key: 'Com', value: 'Comoros' },
        { key: 'Con', value: 'Congo' },
        { key: 'Con', value: 'Congo, the Democratic Republic of the' },
        { key: 'Coo', value: 'Cook Islands' },
        { key: 'Cos', value: 'Costa Rica' },
        { key: 'Côt', value: "Côte d'Ivoi" },
        { key: 'Cro', value: 'Croatia' },
        { key: 'Cub', value: 'Cuba' },
        { key: 'Cur', value: 'Curaçao' },
        { key: 'Cyp', value: 'Cyprus' },
        { key: 'Cze', value: 'Czech Republic' },
        { key: 'Den', value: 'Denmark' },
        { key: 'Dji', value: 'Djibouti' },
        { key: 'Dom', value: 'Dominica' },
        { key: 'Dom', value: 'Dominican Republic' },
        { key: 'Ecu', value: 'Ecuador' },
        { key: 'Egy', value: 'Egypt' },
        { key: 'El ', value: 'El Salvador' },
        { key: 'Equ', value: 'Equatorial Guinea' },
        { key: 'Eri', value: 'Eritrea' },
        { key: 'Est', value: 'Estonia' },
        { key: 'Eth', value: 'Ethiopia' },
        { key: 'Fal', value: 'Falkland Islands(Malvinas)' },
        { key: 'Far', value: 'Faroe Islands' },
        { key: 'Fij', value: 'Fiji' },
        { key: 'Fin', value: 'Finland' },
        { key: 'Fra', value: 'France' },
        { key: 'Fre', value: 'French Guiana' },
        { key: 'Fre', value: 'French Polynesia' },
        { key: 'Fre', value: 'French Southern Territories' },
        { key: 'Gab', value: 'Gabon' },
        { key: 'Gam', value: 'Gambia' },
        { key: 'Geo', value: 'Georgia' },
        { key: 'Ger', value: 'Germany' },
        { key: 'Gha', value: 'Ghana' },
        { key: 'Gib', value: 'Gibraltar' },
        { key: 'Gre', value: 'Greece' },
        { key: 'Gre', value: 'Greenland' },
        { key: 'Gre', value: 'Grenada' },
        { key: 'Gua', value: 'Guadeloupe' },
        { key: 'Gua', value: 'Guam' },
        { key: 'Gua', value: 'Guatemala' },
        { key: 'Gue', value: 'Guernsey' },
        { key: 'Gui', value: 'Guinea' },
        { key: 'Gui', value: 'Guinea - Bissau' },
        { key: 'Guy', value: 'Guyana' },
        { key: 'Hai', value: 'Haiti' },
        { key: 'Hea', value: 'Heard Island and McDonald Islands' },
        { key: 'Hol', value: 'Holy See(Vatican City State)' },
        { key: 'Hon', value: 'Honduras' },
        { key: 'Hon', value: 'Hong Kong' },
        { key: 'Hun', value: 'Hungary' },
        { key: 'Ice', value: 'Iceland' },
        { key: 'Ind', value: 'India' },
        { key: 'Ind', value: 'Indonesia' },
        { key: 'Ira', value: 'Iran, Islamic Republic of' },
        { key: 'Ira', value: 'Iraq' },
        { key: 'Ire', value: 'Ireland' },
        { key: 'Isl', value: 'Isle of Man' },
        { key: 'Isr', value: 'Israel' },
        { key: 'Ita', value: 'Italy' },
        { key: 'Jam', value: 'Jamaica' },
        { key: 'Jap', value: 'Japan' },
        { key: 'Jer', value: 'Jersey' },
        { key: 'Jor', value: 'Jordan' },
        { key: 'Kaz', value: 'Kazakhstan' },
        { key: 'Ken', value: 'Kenya' },
        { key: 'Kir', value: 'Kiribati' },
        { key: 'Kor', value: "Korea, Democratic People's Republic " },
        { key: 'Kor', value: 'Korea, Republic of' },
        { key: 'Kuw', value: 'Kuwait' },
        { key: 'Kyr', value: 'Kyrgyzstan' },
        { key: 'Lao', value: "Lao People's Democratic Republ" },
        { key: 'Lat', value: 'Latvia' },
        { key: 'Leb', value: 'Lebanon' },
        { key: 'Les', value: 'Lesotho' },
        { key: 'Lib', value: 'Liberia' },
        { key: 'Lib', value: 'Libya' },
        { key: 'Lie', value: 'Liechtenstein' },
        { key: 'Lit', value: 'Lithuania' },
        { key: 'Lux', value: 'Luxembourg' },
        { key: 'Mac', value: 'Macao' },
        { key: 'Mac', value: 'Macedonia, the former Yugoslav Republic of' },
        { key: 'Mad', value: 'Madagascar' },
        { key: 'Mal', value: 'Malawi' },
        { key: 'Mal', value: 'Malaysia' },
        { key: 'Mal', value: 'Maldives' },
        { key: 'Mal', value: 'Mali' },
        { key: 'Mal', value: 'Malta' },
        { key: 'Mar', value: 'Marshall Islands' },
        { key: 'Mar', value: 'Martinique' },
        { key: 'Mau', value: 'Mauritania' },
        { key: 'Mau', value: 'Mauritius' },
        { key: 'May', value: 'Mayotte' },
        { key: 'Mex', value: 'Mexico' },
        { key: 'Mic', value: 'Micronesia, Federated States of' },
        { key: 'Mol', value: 'Moldova, Republic of' },
        { key: 'Mon', value: 'Monaco' },
        { key: 'Mon', value: 'Mongolia' },
        { key: 'Mon', value: 'Montenegro' },
        { key: 'Mon', value: 'Montserrat' },
        { key: 'Mor', value: 'Morocco' },
        { key: 'Moz', value: 'Mozambique' },
        { key: 'Mya', value: 'Myanmar' },
        { key: 'Nam', value: 'Namibia' },
        { key: 'Nau', value: 'Nauru' },
        { key: 'Nep', value: 'Nepal' },
        { key: 'Net', value: 'Netherlands' },
        { key: 'New', value: 'New Caledonia' },
        { key: 'New', value: 'New Zealand' },
        { key: 'Nic', value: 'Nicaragua' },
        { key: 'Nig', value: 'Niger' },
        { key: 'Nig', value: 'Nigeria' },
        { key: 'Niu', value: 'Niue' },
        { key: 'Nor', value: 'Norfolk Island' },
        { key: 'Nor', value: 'Northern Mariana Islands' },
        { key: 'Nor', value: 'Norway' },
        { key: 'Oma', value: 'Oman' },
        { key: 'Pak', value: 'Pakistan' },
        { key: 'Pal', value: 'Palau' },
        { key: 'Pal', value: 'Palestinian Territory, Occupied' },
        { key: 'Pan', value: 'Panama' },
        { key: 'Pap', value: 'Papua New Guinea' },
        { key: 'Par', value: 'Paraguay' },
        { key: 'Per', value: 'Peru' },
        { key: 'Phi', value: 'Philippines' },
        { key: 'Pit', value: 'Pitcairn' },
        { key: 'Pol', value: 'Poland' },
        { key: 'Por', value: 'Portugal' },
        { key: 'Pue', value: 'Puerto Rico' },
        { key: 'Qat', value: 'Qatar' },
        { key: 'Réu', value: 'Réunion' },
        { key: 'Rom', value: 'Romania' },
        { key: 'Rus', value: 'Russian Federation' },
        { key: 'Rwa', value: 'Rwanda' },
        { key: 'Sai', value: 'Saint Barthélemy' },
        { key: 'Sai', value: 'Saint Helena, Ascension and Tristan da Cunha' },
        { key: 'Sai', value: 'Saint Kitts and Nevis' },
        { key: 'Sai', value: 'Saint Lucia' },
        { key: 'Sai', value: 'Saint Martin(French part)' },
        { key: 'Sai', value: 'Saint Pierre and Miquelon' },
        { key: 'Sai', value: 'Saint Vincent and the Grenadines' },
        { key: 'Sam', value: 'Samoa' },
        { key: 'San', value: 'San Marino' },
        { key: 'Sao', value: 'Sao Tome and Principe' },
        { key: 'Sau', value: 'Saudi Arabia' },
        { key: 'Sen', value: 'Senegal' },
        { key: 'Ser', value: 'Serbia' },
        { key: 'Sey', value: 'Seychelles' },
        { key: 'Sie', value: 'Sierra Leone' },
        { key: 'Sin', value: 'Singapore' },
        { key: 'Sin', value: 'Sint Maarten(Dutch part)' },
        { key: 'Slo', value: 'Slovakia' },
        { key: 'Slo', value: 'Slovenia' },
        { key: 'Sol', value: 'Solomon Islands' },
        { key: 'Som', value: 'Somalia' },
        { key: 'Sou', value: 'South Africa' },
        { key: 'Sou', value: 'South Georgia and the South Sandwich Islands' },
        { key: 'Sou', value: 'South Sudan' },
        { key: 'Spa', value: 'Spain' },
        { key: 'Sri', value: 'Sri Lanka' },
        { key: 'Sud', value: 'Sudan' },
        { key: 'Sur', value: 'Suriname' },
        { key: 'Sva', value: 'Svalbard and Jan Mayen' },
        { key: 'Swa', value: 'Swaziland' },
        { key: 'Swe', value: 'Sweden' },
        { key: 'Swi', value: 'Switzerland' },
        { key: 'Syr', value: 'Syrian Arab Republic' },
        { key: 'Tai', value: 'Taiwan, Province of China' },
        { key: 'Taj', value: 'Tajikistan' },
        { key: 'Tan', value: 'Tanzania, United Republic of' },
        { key: 'Tha', value: 'Thailand' },
        { key: 'Tim', value: 'Timor - Leste' },
        { key: 'Tog', value: 'Togo' },
        { key: 'Tok', value: 'Tokelau' },
        { key: 'Ton', value: 'Tonga' },
        { key: 'Tri', value: 'Trinidad and Tobago' },
        { key: 'Tun', value: 'Tunisia' },
        { key: 'Tur', value: 'Turkey' },
        { key: 'Tur', value: 'Turkmenistan' },
        { key: 'Tur', value: 'Turks and Caicos Islands' },
        { key: 'Tuv', value: 'Tuvalu' },
        { key: 'Uga', value: 'Uganda' },
        { key: 'Ukr', value: 'Ukraine' },
        { key: 'Uni', value: 'United Arab Emirates' },
        { key: 'Uni', value: 'United Kingdom' },
        { key: 'Uni', value: 'United States' },
        { key: 'Uni', value: 'United States Minor Outlying Islands' },
        { key: 'Uru', value: 'Uruguay' },
        { key: 'Uzb', value: 'Uzbekistan' },
        { key: 'Van', value: 'Vanuatu' },
        { key: 'Ven', value: 'Venezuela, Bolivarian Republic of' },
        { key: 'Vie', value: 'Viet Nam' },
        { key: 'Vir', value: 'Virgin Islands, British' },
        { key: 'Vir', value: 'Virgin Islands, U.S' },
        { key: 'Wal', value: 'Wallis and Futuna' },
        { key: 'Wes', value: 'Western Sahara' },
        { key: 'Yem', value: 'Yemen' },
        { key: 'Zam', value: 'Zambia' },
        { key: 'Zim', value: 'Zimbabwe' }
    ];

    constructor(options: {} = {}) {
        super(options);
        this.type = 'country';
    }
}
